### ISSUE TITLE
Running wsas-analysis.py

### ISSUE THREAD

**Issue by bieniekmateusz** [UCL-CCS/BAC2#68]
Hi Dave, 

We are trying to run your wsas-analysis.py. Initially it was missing the advanced_property. I had a quick look through the history in the repository and it seems like it was taken out at some point. So I put it back just to get the code working. 

Now I am trying to use it. I use the BAC2/examples/namd_esmacs and try to apply it there. 
`python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st complex.top -o test`
This complains during validation of lig_top. So I added the lig top, and I select the lig component, and added the trajectory of the complex (which I think is a single frame pdb)
`python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st complex.top -lt lig.top -c ligand -t complex.pdb -o test`
 
This takes me to:
`(bac2) uccamkb@proline:~/BAC2/examples/namd_esmacs/build$ python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st complex.top -lt lig.top -c ligand -t complex.pdb -o test
/home/uccamkb/miniconda3/envs/bac2/lib/python3.8/site-packages/mdtraj/core/trajectory.py:419: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')
FreeSASA:lib/src/structure.c:679: error: input had no valid ATOM or HETATM lines
FreeSASA:lib/src/structure.c:686: error: 
Traceback (most recent call last):
  File "/home/uccamkb/BAC2/bac/analyse/wsas/wsas-analysis.py", line 134, in <module>
    wsas_calculator.calc_surface_areas()
  File "/home/uccamkb/BAC2/bac/analyse/wsas/wsas.py", line 159, in calc_surface_areas
    atom_areas = pd.DataFrame(sasa_calculator.run(trajectory_pdb))
  File "/home/uccamkb/BAC2/bac/analyse/wsas/freesasa_utils.py", line 93, in run
    structure_array = freesasa.structureArray(bytes(pdb, 'utf-8'), options=self.options, classifier=self.classifier)
  File "freesasa.pyx", line 808, in freesasa.structureArray
Exception: Problems reading structures in 'b'/tmp/tmpz_9jubta/ligand-traj.pdb''.`

Am I using your class correctly? I could not find an example in the /examples directory.

**Comment by dww100** [comment]
Okay so several things appear to be wrong and I get different errors (probably freesasa version related). The `UserWarning`s appear to be nothing to worry about (in that mdtraj isn't doing anything different and it should work - though in some situations it is something to be wary about).

What does your '/tmp/tmpz_9jubta/ligand-traj.pdb' file look like?

**Comment by dww100** [comment]
My memory is that you shouldn't have to pass a ligand trajectory file in the CLI - the option should be to have that or a ligand filter.

**Comment by dww100** [comment]
I also think you want to be using the 'complex' component.

This is looking like something may have changed in the component selection code in mdtraj.

**Comment by dww100** [comment]
I'll try to look at this later but I can't be super responsive - if you put things here though I will look at them.

**Comment by bieniekmateusz** [comment]
Thanks

The file `/tmp/tmpz_9jubta/ligand-traj.pdb` contains only `END`. 

I'll try passing the -lf ligand_filter. 

The freesasa version has changed. I should add that rather carelessly I removed the configuration parts that it was not accepting anymore. I'll check that too.

**Comment by dww100** [comment]
That was what I was suspecting - the filtering to create sub trajectories is going wrong somehow.

**Comment by bieniekmateusz** [comment]
I set the -lf as "resname AEE" which I found in the complex. Now I am going to apply the validate_prmtop only if the lig_top was passed in the command. .

**Comment by bieniekmateusz** [comment]
`python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st complex.top -lf "resname AEE" -c complex -t complex.pdb -o test`

With the -lf the selection is still not properly applied. I checked in console and the selection works fine in mdtraj. I'll check where it goes wrong then.

**Comment by bieniekmateusz** [comment]
# the following is the filter applied to a receptor, it seems that my "resname AEE" did not make it there:

```
filter ! ((resname =~ WAT) or (resname =~ HOH) or (resname =~ 'Cl.*') or (resname =~ CIO) or (resname =~ 'Cs+') or (resname =~ IB) or (resname =~ 'K.*') or (resname =~ 'Li+') or (resname =~ 'MG.*') or (resname =~ 'Na+') or (resname =~ 'Rb+') or (resname =~ CS) or (resname =~ RB) or (resname =~ NA) or (resname =~ F) or (resname =~ ZN)) 
component receptor 
sel [   0    1    2 ... 4723 4724 4725]
```

**Comment by bieniekmateusz** [comment]
Apparently -c recceptor does not set a filters['ligand']. Switching to -c complex, then the receptor applies the ligand filter. So there are two: 'complex' and 'receptor'. For some reason though, sasa is looking for /tmp/tmpqz89fji1/ligand-traj.pdb which is a ligand traj, which we should not need I think. 

So just before saving, I check what is being saved: 
comp_traj <mdtraj.Trajectory with 0 frames, 65 atoms, 1 residues, without unitcells>

So no frames. So in this case, it is the slicing, apparently when applied on mdtraj:
mdtraj[0:-1] means that a trajectoryis not selected. This is sadly consistent with how lists behave.

Correcting the python slice to have defaults slice(0, None, 1)

**Comment by bieniekmateusz** [comment]
So the next step is to set correctly the default vdw and others. I'll check the git history and update that. 
```
Traceback (most recent call last):
  File "/home/uccamkb/BAC2/bac/analyse/wsas/wsas-analysis.py", line 133, in <module>
    wsas_calculator.calc_surface_areas()
  File "/home/uccamkb/BAC2/bac/analyse/wsas/wsas.py", line 159, in calc_surface_areas
    atom_areas = pd.DataFrame(sasa_calculator.run(trajectory_pdb))
  File "/home/uccamkb/BAC2/bac/analyse/wsas/freesasa_utils.py", line 93, in run
    structure_array = freesasa.structureArray(bytes(pdb, 'utf-8'), options=self.options, classifier=self.classifier)
  File "freesasa.pyx", line 814, in freesasa.structureArray
  File "freesasa.pyx", line 556, in freesasa.Structure.setRadiiWithClassifier
  File "freesasa.pyx", line 577, in freesasa.Structure.setRadii
AssertionError
```

**Comment by dww100** [comment]
I think some background is needed here:
Standard 1 traj MMPBSA/ESMACS produces complex trajectories only - to get WSAS values you extract the Complex, the Receptor and the Ligand trajectories without water, values are then calculated as C - R - L

The 'receptor' and 'ligand' options are for computing values for just R or L from trajectories with only the protein or ligand in them to sub in for the values which you would obtain from the complex trajectory (R and L above).

Does that make sense?

So at some point a complex run should look for a ligand trajectory.

**Comment by bieniekmateusz** [comment]
That makes sense. Thanks^

**Comment by bieniekmateusz** [comment]
Updated reference to the latest freesasa.Parameters.defaultParameters - e2c06cf68d2dc220e6a6a05dfbeaef1c6635f906

However, the freessa is not making correct use of the parameters so something else must have changed.

**Comment by bieniekmateusz** [comment]
The problem lies in the classifier when it is used to convert PDB to structure by freesasa. Removing the classifier (and therefore using the default) works fine. Let's see what we lost in this process.

**Comment by bieniekmateusz** [comment]
I am not sure what it is sasa does not like in the config file. I tried the default https://github.com/mittinatten/freesasa/blob/master/share/protor.config and it seems to throw the same error. However, leaving it without the classifier appears to work fine.

**Comment by bieniekmateusz** [comment]
So there must be an atom type that we do not cover and that is used.

**Comment by bieniekmateusz** [comment]
Hey @dww100 , the error is swallowed and does not say what is the issue. I've compiled the sasa and used it with the configuration file, and then use it on the entire complex, and that worked fine:
```
./freesasa --config-file=/home/dresio/code/freesasa-2.0.3/share/protor.config  /home/dresio/code/BAC2/examples/namd_esmacs/build/complex.pdb

PARAMETERS
algorithm    : Lee & Richards
probe-radius : 1.400
threads      : 2
slices       : 20

INPUT
source  : /home/dresio/code/BAC2/examples/namd_esmacs/build/complex.pdb
chains  :  
model   : 1
atoms   : 17225

RESULTS (A^2)
Total   :   65257.68
Apolar  :    2621.47
Polar   :    1645.66
Unknown :   60990.55
CHAIN   :   65257.68
```

When I switched to your amber_config.txt for freesasa, it worked fine too. However, when I try to create a classifier myself from any of the config files, and then use the freesasa.structureArray function, 

```
AssertionError                            Traceback (most recent call last)
<ipython-input-28-fc84e8acfe37> in <module>
----> 1 sa = freesasa.structureArray('complex.pdb', classifier=cla)

freesasa.pyx in freesasa.structureArray()
freesasa.pyx in freesasa.Structure.setRadiiWithClassifier()
freesasa.pyx in freesasa.Structure.setRadii()
AssertionError: 
```

This does not happen if I ignore the classifier parameter in freesasa.structureArray

**Comment by bieniekmateusz** [comment]
Here are the slightly different results when using your config file:
```
PARAMETERS
algorithm    : Lee & Richards
probe-radius : 1.400
threads      : 2
slices       : 20

INPUT
source  : /home/dresio/code/BAC2/examples/namd_esmacs/build/complex.pdb
chains  :  
model   : 1
atoms   : 17225

RESULTS (A^2)
Total   :   66425.23
Apolar  :    3134.14
Polar   :    1879.79
Unknown :   61411.30
CHAIN   :   66425.23

```

**Comment by bieniekmateusz** [comment]
Python2, freesasa-2.0.3.post7.tar.gz, suffer from the same issue. 
The compiler version has FreeSASA 2.0.3

So it seems like a bug related to how the classifier is used within the structured array.

**Comment by bieniekmateusz** [comment]
All versions that still can be installed suffer from this error. I'll do one more check and then I'll introduce a workaround in which we would call our own freesasa compiled version. Ie the binary version in the settings. Let me know why that would not be a good idea @dww100

**Comment by bieniekmateusz** [comment]
I found what the error is connected to: freesasa.structureArray cannot take a pdb with just one frame. For a single frame, freesasa.Structure has to be used: which then creates its own issues. I'll take a small simulation to test it again now.

**Comment by bieniekmateusz** [comment]
So I've switched to my files:
`python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st morph_solv.top -lf "resname gle" -c complex -t prod.dcd -o wsas`

That leads to another in mdtraj
```
  File "/home/uccamkb/BAC2/bac/analyse/wsas/wsas-analysis.py", line 133, in <module>
    wsas_calculator.calc_surface_areas()
  File "/home/uccamkb/BAC2/bac/analyse/wsas/wsas.py", line 155, in calc_surface_areas
    comp_traj = traj[self.slice].atom_slice(atom_list)
  File "/home/uccamkb/miniconda3/envs/bac2/lib/python3.8/site-packages/mdtraj/core/trajectory.py", line 1714, in atom_slice
    xyz = np.array(self.xyz[:, atom_indices], order='C')
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by bieniekmateusz** [comment]
At the end, this turned to be wrong too. I used my own trajectory so this time it was not just one frame: and the same error was found. 

So if I do this:
import freesasa
c =freesasa.Classifier('/home/dresio/code/BAC2/bac/analyse/wsas/data/amber_config.txt')
freesasa.structureArray('/home/dresio/code/BAC2/examples/namd_esmacs/build/complex.pdb', classifier=c)

This ends in 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "freesasa.pyx", line 775, in freesasa.structureArray (freesasa.c:8289)
  File "freesasa.pyx", line 519, in freesasa.Structure.setRadiiWithClassifier (freesasa.c:5458)
  File "freesasa.pyx", line 540, in freesasa.Structure.setRadii (freesasa.c:5750)
AssertionError


But if I test which atom has a radii setting problem:
import freesasa
c =freesasa.Classifier('/home/dresio/code/BAC2/bac/analyse/wsas/data/amber_config.txt')
import MDAnalysis as mda
u = mda.Universe('/home/dresio/code/BAC2/examples/namd_esmacs/build/complex.pdb')
aee = u.select_atoms('resname AEE')
for atom in aee:
	print(atom.resname, atom.name)
	c.radius(atom.resname, atom.name)
# getting radius
for atom in u.atoms:
	c.radius(atom.resname, atom.name)

The all the radii are fine. So the error is somewhere else.

**Comment by bieniekmateusz** [comment]
Another twist, when I extract the temporary .pdb file of the ligand, and then apply the script with the right config file:
`./freesasa --config-file=/home/dresio/code/BAC2/bac/analyse/wsas/data/amber_config.txt  sasa_ligand.pdb`

It is incapable of finding anything for the resnames:
```
....
 FreeSASA: warning: atom 'ged  C28' unknown and can't guess radius of symbol 'C ', assigning radius 0 A
FreeSASA: warning: atom 'ged CL2 ' unknown and can't guess radius of symbol 'Cl', assigning radius 0 A
FreeSASA: warning: atom 'ged  N1 ' unknown and can't guess radius of symbol 'N ', assigning radius 0 A
```

**Comment by bieniekmateusz** [comment]
So none of the .config files work by default because of the resname. I've been mistaking radii value -1 as a value, which is actually an indicator of an error.

**Comment by bieniekmateusz** [comment]
I've been mistaking the radii -1 as not an error. It seems that I need some more general rule for the config file in order to capture non-standard residues/ligands.

**Comment by dww100** [comment]
This seems like some effort - I'll talk to Peter and see if i can make a deal which ends up with me being able to spend some time on it.

**Comment by bieniekmateusz** [comment]
Well, I think I am close to the solution now. I think I have to make sure that the generated atom name by amber is in the pdb used by the freesasa.

**Comment by dww100** [comment]
That makes sense. Which version of freesasa are you using now?

**Comment by bieniekmateusz** [comment]
These are available: 2.0.2b1, 2.0.2b2, 2.0.3, 2.0.3.post1, 2.0.3.post2, 2.0.3.post3, 2.0.3.post6, 2.0.3.post7

But without errors only these could be installed 2.0.3.post1, 2.0.3.post2, 2.0.3.post3, 2.0.3.post6, 2.0.3.post7, I tried all.

**Comment by bieniekmateusz** [comment]
So for example, in atoms:
ANY N1 N
Removes the problem: 
warning: atom 'ged  N1 ' unknown and can't guess radius of symbol 'N ', assigning radius 0 A

So at the end, I have to match these. 

Ideally, I would source all the information from the topology, since it has the radii, and charges. And use a cutoff value to say whether it is polar or apolar.

**Comment by bieniekmateusz** [comment]
Hi @shunzhou , for the ligands that we parametrise using ambertools, I need each atom's radius from the amber topology file. This will be used for SASA calculation. 

I see that there is a RADII flag in the topology, which is described in the documentation as 
```
%FLAG RADII
%FORMAT(5E16.8) (RBORN(i), i=1,NATOM)
  RBORN  : Generalized Born intrinsic dielectric radii
```

will this be a good value to use?

**Comment by bieniekmateusz** [comment]
For the water molecules, it is 1.5 for oxygen, and 0.8 for hydrogens.

**Comment by bieniekmateusz** [comment]
SASA requires each atom to be classified as polar or apolar,

So the question is, using the amber topology, and the charges assigned, which we know, what is the cutoff at which we would clasiffy an atom as apolar.

**Comment by bieniekmateusz** [comment]
Just in case I run the same code with the ligand topology -lt, but it seems that whatever update is being done to the sasa.config file, it does not make it: 
python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st morph_solv.top -lt ged.prmtop -c complex  -t prod.dcd -o sasa

**Comment by bieniekmateusz** [comment]
So in the first case, the ligand now works:
`python ~/BAC2/bac/analyse/wsas/wsas-analysis.py -st morph_solv.top -lf "resname ged" -c ligand  -t prod.dcd -o sasa -n ged.prmtop`

Which had in summary 64.04572372956488
And then there is the break down per each atom. 

For the complex, a similar thing will have to be done. Let us see if -n is more general.

**Comment by shunzhou** [comment]
> Hi @shunzhou , for the ligands that we parametrise using ambertools, I need each atom's radius from the amber topology file. This will be used for SASA calculation.
> 
> I see that there is a RADII flag in the topology, which is described in the documentation as
> 
> ```
> %FLAG RADII
> %FORMAT(5E16.8) (RBORN(i), i=1,NATOM)
>   RBORN  : Generalized Born intrinsic dielectric radii
> ```
> 
> will this be a good value to use?

I'm not sure what radii are required. Is it vdW radii or generalised Born radii? I assume vdW radii are what you need, which can be found in the Amber parameter files such like parm99.dat and gaff.dat.

**Comment by bieniekmateusz** [comment]
I see. @shunzhou , I noticed that some atoms have a highly atypical type that starts with a digit, such as '2C'. Is there anything special about these atoms? Becaue they are not in the wang2012 paper and are causing us trouble.

**Comment by bieniekmateusz** [comment]
Scratch that, it is a bug in parmed.

**Comment by bieniekmateusz** [comment]
Apparently the amber atom types can begin really numbers. 

```
%FORMAT(20a4)                                                                   
c   c3  c3  c3  ca  ca  ca  ca  ca  ca  ca  ca  ca  ca  ca  ca  ca  cd  ha  ha  
ha  ha  ha  ha  ha  ha  ha  hc  hc  hc  hc  h1  h1  o   o   os  cc  ca  ca  ca  
ha  cl  os  cc  ca  ca  ca  cl  ha  na  hn  N3  H   H   H   CX  HP  HP  C   O   
N   H   CX  H1  2C  HC  HC  CO  O2  O2  C   O   N   H   CX  H1  2C  HC  HC  2C  
HC  HC  CO  O2  O2  C   O   N   H   CX  H1  2C  HC  HC  3C  HC  CT  HC  HC  HC  
CT  HC  HC  HC  C   O   N   H
```

**Comment by bieniekmateusz** [comment]
When I run the ./freesasa, the only resolution that is missing is this:
## FreeSASA 2.0.3 ##
FreeSASA: warning: atom 'HIS  OXT' unknown and can't guess radius of symbol 'O ', assigning radius 0 A

**Comment by bieniekmateusz** [comment]
So if I add a resolution for this, it should be fine. Ideally, this would rely on the weights in the main wsas file.

**Comment by bieniekmateusz** [comment]
Each of the other residue OXT atoms maps to the same atom. Therefore, the added rule is HYP OXT O2H1

**Comment by bieniekmateusz** [comment]
This should be updated to ANY rule. With this modification, the SASA works on the complex when run the binary, but the actual still gets stuck on the classifier and cannot set radii on something (ligand works fine, just the complex)

**Comment by shunzhou** [comment]
The atom names for standard amino acid in Amber don’t start with a number; they always start with a letter indicating what atoms they are (C, N, O …). The names in ligand are artificially given; you can give them whatever you like, staring with numbers of letters; they may need to be no longer than 4 letters/digits.

It appears that freeasa decides the atom types based on their names, and does not read them from the amber topology. Is my understanding correct?

The OXT has the same atom type as O in standard amino acid.


On 24 Mar 2020, at 08:22, Mateusz Bieniek <notifications@github.com<mailto:notifications@github.com>> wrote:



This should be updated to ANY rule. With this modification, the SASA works on the complex when run the binary, but the actual still gets stuck on the classifier and cannot set radii on something (ligand works fine, just the complex)

**Comment by bieniekmateusz** [comment]
Thanks @shunzhou , the atom names starting with a digit turned out to be a bug in the package parmed. 

I have it working for ligand only. And there was one missing atom which I added as you say: just an oxygen really.

**Comment by bieniekmateusz** [comment]
I also have now a basic version that does it correctly on my computer. So the next thing I have to figure out why it breaks in the same situation on proline with WSAS.

**Comment by bieniekmateusz** [comment]
Also, @shunzhou , yes - by default it reads a .pdb file right now, and then it uses a "classifier" to map the pdb names (residue names and atom name) to radius and polarity

**Comment by bieniekmateusz** [comment]
So the ipython procedure works with all the files. And yet the software crashes. 

I've modified freesasa-python to extract better messages. The next residue that breaks down is
AssertionError: radius array is 0 or below for resname HIS atom  HD1

**Comment by bieniekmateusz** [comment]
I have a full prootype working. The last issue is to solve the WSAS contribution calculation.

**Comment by dww100** [comment]
I think that amber should never have HIS residues - histidines are HIE, HID or HIP depending on protonation. So the HIS appearing there is bit of a potential worry (unless it is an understood freesasa work around I have forgotten about).

**Comment by bieniekmateusz** [comment]
Good point. It is the mdtraj that makes the writing of the trajectory. It it possible that mdtraj simplifies the .pdb representation: it might be reading the amber topology and reading these types as HIS. I'll check now.

**Comment by bieniekmateusz** [comment]
@dww100 , do you know if wsas-params-wang2012.json can have its keys capitilised? I cannot image them being case sensivite

**Comment by dww100** [comment]
IIRC the keys match the AMBER distinction - I think lower case is the atom types from the GAFF part of the forcefield.

**Comment by bieniekmateusz** [comment]
I've just tried to apply set on the upper and that did reduce the number of the keys.

**Comment by bieniekmateusz** [comment]
there is a couple of atom types that cannot be found: {' 2C', ' 3C', ' C8', ' CO', ' CX', 'CX'}, I'll check where they are coming from

**Comment by dww100** [comment]
What I don't remember is what we did to map the types to the parameters given in the Wang paper for the amino acid atoms.

**Comment by dww100** [comment]
Can't be found meaning aren't in wsas-params-wang2012.json?

It is possible that new atom types have come in to new version of the Amber forcefield or GAFF (or is @shunzhou using OpenFF?

**Comment by bieniekmateusz** [comment]
ohh, I see, i think this is a bug in parmed - for some reason it finds the atom type, and does not separate it correctly,

**Comment by dww100** [comment]
Is parmed using a topology or some mangled PDB to get atom types in this instance?

**Comment by bieniekmateusz** [comment]
It is using a ambertools generated topology that was used in a series of simulations

**Comment by bieniekmateusz** [comment]
[topo.tar.gz](https://github.com/UCL-CCS/BAC2/files/4374763/topo.tar.gz)

**Comment by bieniekmateusz** [comment]
Freesasa-python is going to change the warnings to make them less confusing. So that's a good thing. 

Also, now we know that atom types can start with digits. And the parmed package did not have a bug in reading it - it was a sloppy test I applied. 

The first version is now running. I have to automate the ligand selection only.
